export const projectsData = [
	{
		title: "ProOxy park, Kopaonik, Serbien Projekt 002",
		location: "Kopaonik, Serbia",
		price: "1.000.000 CHF",
		certification: "TUF NORD / ab 2022 Gold Standard (in Process)",
		projectBenefit: "UN-NachhaltikeitSziele",
		categories: [
			"Aufforstung",
			"Biodivesitat",
			"Klimaschutz",
			"Soziale Forderung",
			"Bildung",
		],
		imageUrl:
			"https://dynamic-media-cdn.tripadvisor.com/media/photo-o/03/7c/b2/2b/kopaonik.jpg",
	},
	{
		title: "Hydro Renewable Energy",
		location: "Kopaonik, Serbia",
		price: "1.000.000 CHF",
		certification: "TUF NORD / ab 2022 Gold Standard (in Process)",
		projectBenefit: "UN-NachhaltikeitSziele",
		categories: [
			"Aufforstung",
			"Biodivesitat",
			"Klimaschutz",
			"Soziale Forderung",
			"Bildung",
		],
		imageUrl:
			"https://www.globalenergyworld.com/NewsImages/b/62878/63472_O.jpg",
	},
	{
		title: "Amazon Forest Conservation1",
		location: "Kopaonik, Serbia",
		price: "1.000.000 CHF",
		certification: "TUF NORD / ab 2022 Gold Standard (in Process)",
		projectBenefit: "UN-NachhaltikeitSziele",
		categories: [
			"Aufforstung",
			"Biodivesitat",
			"Klimaschutz",
			"Soziale Forderung",
			"Bildung",
		],
		imageUrl: "https://www.chicp.co.uk/cdn/shop/articles/rainforest.png",
	},
	{
		title: "ProOxy park, Kopaonik, Serbien Projekt 001",
		location: "Kopaonik, Serbia",
		price: "1.000.000 CHF",
		certification: "TUF NORD / ab 2022 Gold Standard (in Process)",
		projectBenefit: "UN-NachhaltikeitSziele",
		categories: [
			"Aufforstung",
			"Biodivesitat",
			"Klimaschutz",
			"Soziale Forderung",
			"Bildung",
		],
		imageUrl:
			"https://dynamic-media-cdn.tripadvisor.com/media/photo-o/03/7c/b2/2b/kopaonik.jpg",
	},
	{
		title: "Hydro Renewable Energy1",
		location: "Kopaonik, Serbia",
		price: "1.000.000 CHF",
		certification: "TUF NORD / ab 2022 Gold Standard (in Process)",
		projectBenefit: "UN-NachhaltikeitSziele",
		categories: [
			"Aufforstung",
			"Biodivesitat",
			"Klimaschutz",
			"Soziale Forderung",
			"Bildung",
		],
		imageUrl:
			"https://www.globalenergyworld.com/NewsImages/b/62878/63472_O.jpg",
	},
	{
		title: "Amazon Forest Conservation",
		location: "Kopaonik, Serbia",
		price: "1.000.000 CHF",
		certification: "TUF NORD / ab 2022 Gold Standard (in Process)",
		projectBenefit: "UN-NachhaltikeitSziele",
		categories: [
			"Aufforstung",
			"Biodivesitat",
			"Klimaschutz",
			"Soziale Forderung",
			"Bildung",
		],
		imageUrl: "https://www.chicp.co.uk/cdn/shop/articles/rainforest.png",
	},
];
